langchain-ai/langchain-aws

libs/aws/langchain_aws/llms/bedrock.py

renders in langsmith: https://smith.langchain.com/public/35edf4ec-dabb-4560-b83e-508d6185b9fa/r?runtab=2

fix identifying params

---

libs/aws/langchain_aws/llms/bedrock.py

Fixed bedrock attributes when using guardrails. See example of usage:
```
from langchain_core.messages import HumanMessage
from langchain_aws.chat_models import ChatBedrock
llm_model_id='anthropic.claude-3-haiku-20240307-v1:0'
chat = ChatBedrock(
model_id=llm_model_id,
streaming=True,
model_kwargs={"temperature": 0.1},
guardrails={"guardrailIdentifier": "identifier", "guardrailVersion": "1", "trace": True},
)
messages = [
HumanMessage(
content="What are the financial advice you can give me?"
)
]
for chunk in chat.stream(messages):
print(chunk.content,  end="", flush=True)
```

fix guardrail attributes when invoking bedrock

---

libs/aws/README.md
libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/function_calling.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Workaround for Bedrock support of function calling with Anthropic models. This change adds that `bind_tools` function to `ChatBedrock`.
```
from bedrock import ChatBedrock
chat = ChatBedrock(
model_id=model_id,
model_kwargs={"temperature": 0.1},
)
class GetWeather(BaseModel):
"""Get the current weather in a given location"""
location: str = Field(..., description="The city and state, e.g. San Francisco, CA")
llm_with_tools = chat.bind_tools([GetWeather])
llm_with_tools
messages = [
HumanMessage(
content="what is the weather like in San Francisco"
)
]
ai_msg = llm_with_tools.invoke(messages)
ai_msg
```
The workaround is implemented similarly to its equivalent directly using Anthropic prior to the feature currently in beta.

Adds support for function calling with Anthropic models on Bedrock

---

libs/aws/README.md
libs/aws/langchain_aws/retrievers/bedrock.py
libs/aws/tests/integration_tests/retrievers/test_amazon_knowledgebases_retriever.py
libs/aws/tests/unit_tests/retrievers/test_bedrock.py

Corresponding PR in langchain: https://github.com/langchain-ai/langchain/pull/21349
- **Description:** Bedrock retrieve API returns extra metadata in the response which is currently not returned in the retriever response
- **Issue:** The change adds the metadata from bedrock retrieve API response to the bedrock retriever in a backward compatible way. Renamed metadata to sourceMetadata as metadata term is being used in the Document already. This is in sync with what we are doing in llama-index as well.
- **Dependencies:** No
1. Added unit tests
2. Notebook already exists and does not need any change
3. Updated and ran integration tests
4. Response from end to end testing, just to ensure backward compatibility: `[Document(page_content='Exoplanets.', metadata={'location': {'s3Location': …

Add source metadata from API response to Document metadata

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Issue described here:
https://github.com/langchain-ai/langchain-aws/issues/31
This is a proposal that will allow to query Llama3 models reliably. The main issue was related to the new tokens required Llama3. If not using them, it will return an empty string for long prompts.

Adding support for Llama3 models in BedrockChat

---

libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/tests/integration_tests/embeddings/test_bedrock_embeddings.py

Support for Titan Embedding v2 with changing embedding sizes based on this [blog](https://aws.amazon.com/blogs/machine-learning/get-started-with-amazon-titan-text-embeddings-v2-a-new-state-of-the-art-embeddings-model-on-amazon-bedrock/). This change lets the user specify `dimension`.
```
from langchain_aws.embeddings import BedrockEmbeddings
prompt_data = """Priority should be funding retirement through ROTH/IRA/401K over HSA extra.  
You need to fund your HSA for reasonable and expected medical expenses. """
bedrock_embedding_model_id = "amazon.titan-embed-text-v2:0"
embed_model = BedrockEmbeddings(model_id=bedrock_embedding_model_id)
response = embed_model.embed_documents([prompt_data], 256, True) 
response = embed_model.embed_query(prompt_data, 512, True)
```

Determine embedding size with Titan Embedding v2 model 

---

libs/aws/langchain_aws/retrievers/bedrock.py
libs/aws/langchain_aws/retrievers/kendra.py
libs/aws/tests/integration_tests/retrievers/test_amazon_knowledgebases_retriever.py
libs/aws/tests/unit_tests/retrievers/test_bedrock.py

- add min_score_confidence field to `AmazonKnowledgeBasesRetriever` class
- add unit tests and integration tests to test score
- update kendra retriver `_filter_by_score_confidence` doc string
Closes: https://github.com/langchain-ai/langchain-aws/issues/48

Add min_score_confidence support for the Bedrock KB retriver

---

libs/aws/langchain_aws/llms/__init__.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

Fixes #55, #56.
All integration tests pass.
```
(base) ➜  aws git:(fix-stop-reason-error) make integration_tests             
poetry run pytest tests/integration_tests/
================================================================== test session starts ==================================================================
platform darwin -- Python 3.9.13, pytest-7.4.4, pluggy-1.5.0
rootdir: /Users/pijain/projects/langchain-aws-dev/langchain-aws/libs/aws
configfile: pyproject.toml
plugins: syrupy-4.6.1, anyio-4.3.0, cov-4.1.0, asyncio-0.23.6
asyncio: mode=auto
collected 34 items                                                                                                                                      
tests/integration_tests/test_compile.py . …
```

Fixes error when stop reason missing in response.

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py
libs/aws/tests/integration_tests/chat_models/test_standard.py

langchain-core 0.2.2 released a standard field to store usage metadata returned from chat model responses, such as input / output token counts. AIMessage objects have a `.usage_metadata` attribute which can hold a [UsageMetadata](https://api.python.langchain.com/en/latest/messages/langchain_core.messages.ai.UsageMetadata.html) dict. For now it is only holding token counts. Standardizing this information makes it simpler to track in monitoring / observability platforms and similar applications.
Here we unpack usage metadata returned by the Bedrock API onto AIMessages generated by chat models.
There are at least two options for implementing this in a streaming context:
1. (Implemented here) Currently, Bedrock streams a final chunk containing usage data in …

ChatBedrock: add usage metadata

---

libs/aws/langchain_aws/embeddings/bedrock.py

This pull request enhances the functionality of the `BedrockEmbeddings` class by adding an optional `config` argument as a `botocore.config.Config` to give more possible configuration for the boto3 client, in the same way as how it is done on the class `ChatBedrock`.
Here an example answer before the change:
```
embedding = BedrockEmbeddings(
model_id="MODEL_ID",
region_name="REGION_NAME",
profile="PROFILE",
)
```
And now after the change:
```
config = BotocoreConfig(
read_timeout=1000,
retries=1,
)
embedding = BedrockEmbeddings(
model_id="MODEL_ID",
region_name="REGION_NAME",
profile="PROFILE",
config=config
)
```
- Added `config` parameter to the class `BedrockEmbeddings`
This change will allow user to configure `BedrockEmbeddings` the same way as  `ChatBedrock`.
This change maintains …

Adding config argument for BedrockEmbeddings

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

The current implementation of `_drop_none` :
```python
def _drop_none(obj: Any) -> Any:
if isinstance(obj, dict):
new = {k: _drop_none(v) for k, v in obj.items() if _drop_none(v) is not None}
return new or None
else:
return obj
```
throws out empty dictionaries. 
```python
_drop_none(
{'tools': [{"toolSpec": {
"name": "Answer",
"description": "Your answer",
"inputSchema": {
"json": {
"type": "object",
"properties": {
"answer": {
"type": "string",
"description": "Your answer"
},
},
"required": ["answer"]
}
}
}},
{'toolSpec':
{
"name": "get_weather",
"description": "Get the current weather in a given location",
"inputSchema": {
"json": {
"type": "object",
"properties": {
"location": {
"type": "string",
"description": "The city and state, e.g. San Francisco, CA"
},
"unit": {
"type": …
```

Fix bug in _drop_none

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Update after https://github.com/langchain-ai/langchain/pull/24038 to support passing model-generated ToolCalls to Tools

aws[patch]: Add ToolCall "type"

---

libs/aws/langchain_aws/retrievers/bedrock.py

This pull request enhances the functionality of the`AmazonKnowledgeBasesRetriever` class by adding optional parameters for the following features (already implemented in [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock-agent-runtime/client/retrieve.html)):
- added `filter` parameter in `VectorSearchConfig` to filter on metadata tags.
- added `overrideSearchType` in `VectorSearchConfig` to override the default search type to be able to choose between 'Default', 'Hybrid' or 'Semantic'
Here an example answer before the change:
```
retriever = AmazonKnowledgeBasesRetriever(
knowledge_base_id="KNOWLEDGE_BASE_ID,
retrieval_config={
"vectorSearchConfiguration": {
"numberOfResults": 4
}
},
)
```
And now after the change:
```
retriever = …
```

Adding bedrock metadata filter and search type parameters

---

libs/aws/langchain_aws/llms/bedrock.py

Fixes ChatBedrock for llama3

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Fixes streaming for anthropic tool call.

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

With this pull request, the `status` field of `ToolMessage` is now being passed to the `converse` api.

Add ToolMessage's status to bedrock message for ChatBedrockConverse

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

As pointed out in https://github.com/langchain-ai/langchain-aws/issues/134#issuecomment-2271433237, some Bedrock models that support streaming tool calls do not properly stream structured output. This is due to our implementation of `with_structured_output`. Here we update the output parsing for models that support streaming tool calls.

bedrock converse[patch]: support streaming in with_structured_output

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

This PR fixes the image type supported by Bedrock Anthropic and other models. It also adds a new type for supporting documents.
```python
from langchain_core.messages import HumanMessage
from langchain_aws import ChatBedrock
llm = ChatBedrock(
model_id="anthropic.claude-3-sonnet-20240229-v1:0",
beta_use_converse_api=True
)
image_path = "images/random-image.jpg"
image_bytes = None
with open(image_path, "rb") as f:
image_bytes = f.read()
messages = [
HumanMessage(
content=[
{
"type": "image",
"image": {
"format": "jpeg",
"source": {
"bytes": image_bytes
}
}
},
"What is this image about?"
]
)
]
llm.invoke(messages)
```
```python
from langchain_core.messages import HumanMessage
from langchain_aws import ChatBedrock
llm = ChatBedrock(
model_id="anthropic.claude-3-sonnet-20240229-v1:0", …
```

Fixes image type, adds document type for ChatBedrockConverse

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Input and output tokens are counted twice for anthropic models:
- Once [during the stream](https://github.com/langchain-ai/langchain-aws/blob/e86b5517428ae7307c444974a98d1d3804395c19/libs/aws/langchain_aws/llms/bedrock.py#L88), as for anthropic models they are reported in `message_start` and `message_delta` chunks;
- Once at `message_stop`, where they are reported in a [amazon-bedrock-invocationMetrics](https://github.com/langchain-ai/langchain-aws/blob/e86b5517428ae7307c444974a98d1d3804395c19/libs/aws/langchain_aws/llms/bedrock.py#L224) field.
Here we remove the counts during the stream, preferring the final reported `invocationMetrics`.
Problem appears to be with claude models. Inspected counts before/after the change with:
```
"anthropic.claude-3-sonnet-20240229-v1:0" …
```

chatbedrock[patch]: remove redundant token counts

---

.github/workflows/_release.yml

add missing arg to `get_min_versions` script

infra[patch]: fix release workflow

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

Make sure supports_tool_choice_values is set whether or not client is passed in

aws[patch]: fix ChatBedrockConverse init

---

libs/aws/poetry.lock
libs/aws/pyproject.toml

Removes version ceiling currently set at v1.35 for boto3.

Removing version ceiling for boto3.

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/langchain_aws/llms/sagemaker_endpoint.py

Motivation:
Old implementation is swallowing botocore exceptions and translating it into `ValueError` exception which complicates handling different errors, some botocore exceptions could be just retried in the user code, whereas  for others the user wants to just trigger alert and re-raise or raise some specific exception. Raising `ValueError` for all botocore exceptions just make it impossible.

fix: raise botocore exceptions

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/llms/test_bedrock.py

`BedrockLLM.validate_environment` shadows its parent `BedrockBase.validate_environment`, so the latter appears not to run.
Resolves https://github.com/langchain-ai/langchain-aws/issues/196

aws[patch]: fix initialization of BedrockLLM without client

---

libs/aws/poetry.lock
libs/aws/pyproject.toml

Release failing on min version checks: https://github.com/langchain-ai/langchain-aws/actions/runs/10949501299/job/30402920688
langchain-core 0.3.2 includes some updates to Bedrock serialization.

aws[patch]: bump core

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

- when using mistral and streaming is enabled,the final chunk includes a stop_reason. There is nothing to say this final chunk doesn't also include some generated text. The existing implementation would result in that final chunk never getting sent back
- this update moves the yield of the metrics chunk after the generation chunk
- also included a change to include invocation metrics for cohere models
Closes #215

Move yield of metrics chunk after generation chunk

---

libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/unit_tests/__snapshots__/test_standard.ambr

This PR updates the dev dependencies, so that folks developing `langchain-aws` v0.1.x are connected with the compatible versions  from `langchain`.

Aligns dev dependencies with langchain v0.2

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

_backport of fix into v0.1 branch_
Move yield of metrics chunk after generation chunk (#216)
- when using mistral and streaming is enabled,the final chunk includes a stop_reason. There is nothing to say this final chunk doesn't also include some generated text. The existing implementation would result in that final chunk never getting sent back
- this update moves the yield of the metrics chunk after the generation chunk
- also included a change to include invocation metrics for cohere models
Closes #215
(cherry picked from commit e2c2f7c790cb3c83631e6bb72300eba4b61bef2b)

Move yield of metrics chunk after generation chunk (#216)

---

libs/aws/langchain_aws/llms/sagemaker_endpoint.py
libs/aws/tests/integration_tests/llms/test_sagemaker_endpoint.py

* add inference component support to SageMaker Endpoint
* add corresponding tests in SageMaker Endpoint integration tests.

add inference component support to SageMaker Endpoint

---

libs/aws/langchain_aws/llms/bedrock.py

This PR addresses an issue where the streaming functionality in ChatBedrock breaks when Bedrock guardrails are applied. The problem was caused by a KeyError in the `_stream_response_to_generation_chunk` method when trying to access the 'stop_sequence' key, which may not always be present in the response structure when guardrails are active.
- Modified the `_stream_response_to_generation_chunk` method in `llms/bedrock.py` to use the `get()` method when accessing dictionary keys that may not always be present.
- Tested the streaming functionality with and without Bedrock guardrails applied.
- Verified that the streaming works correctly in both scenarios without raising KeyErrors.

Fix streaming functionality with Bedrock guardrails (#176)

---

libs/aws/langchain_aws/llms/bedrock.py

This PR addresses an issue where the streaming functionality in ChatBedrock breaks when Bedrock guardrails are applied. The problem was caused by a KeyError in the `_stream_response_to_generation_chunk` method when trying to access the 'stop_sequence' key, which may not always be present in the response structure when guardrails are active.
- Modified the `_stream_response_to_generation_chunk` method in `llms/bedrock.py` to use the `get()` method when accessing dictionary keys that may not always be present.
- Tested the streaming functionality with and without Bedrock guardrails applied.
- Verified that the streaming works correctly in both scenarios without raising KeyErrors.

Backport v0.1 - PR #177 - Fix streaming functionality with Bedrock guardrails (#176) 

---

libs/aws/langchain_aws/retrievers/bedrock.py
libs/aws/tests/unit_tests/retrievers/test_bedrock.py

Fixed the issue mentioned in https://github.com/langchain-ai/langchain-aws/issues/169
Added unit test that would expose the bug in source code
Tested with my service code and it works with the change

[#169] Fix the broken in operator in bedrock knowledge base retriever.

---

libs/aws/langchain_aws/chat_models/bedrock.py

Fixes #240
Fixes #217 
```python
from langchain_aws import ChatBedrock
from langchain.callbacks.base import BaseCallbackHandler
from langchain_core.prompts import ChatPromptTemplate
streaming = True
class MyCustomHandler(BaseCallbackHandler):
def on_llm_new_token(self, token: str, **kwargs) -> None:
print(f"My custom handler, token: {token}")
prompt = ChatPromptTemplate.from_messages(["Tell me a joke about {animal} in a few words."])
model = ChatBedrock(
model_id="anthropic.claude-3-haiku-20240307-v1:0",
streaming = streaming, 
callbacks=[MyCustomHandler()]
)
chain = prompt | model
response = chain.invoke({"animal": "bears"})
```
```
My custom handler, token: 
My custom handler, token: Bear
My custom handler, token: -
My custom handler, token: ly funny
My custom handler, token: .
My …
```

Fixes token logging in callbacks when streaming=True is used.

---

libs/aws/tests/integration_tests/chat_models/test_standard.py

Some of the tests marked `xfail` are passing in my local testing. Enabling them, so these run during the release.
```shell
tests/integration_tests/chat_models/test_standard.py::TestBedrockStandard::test_tool_message_histories_string_content PASSED
tests/integration_tests/chat_models/test_standard.py::TestBedrockStandard::test_tool_message_histories_list_content PASSED
tests/integration_tests/chat_models/test_standard.py::TestBedrockStandard::test_structured_few_shot_examples PASSED
```

Remove xfail from passing integration tests.

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes #239 
1. Fixes streaming for cross-region inference models ids. 
2. Adds support for Cohere models in ChatBedrockConverse.
3. Also, adds standard integration tests for Cohere.

Fixes support for cross region inference

---

libs/aws/langchain_aws/llms/bedrock.py

The guardrails attributes were changed in https://github.com/langchain-ai/langchain-aws/pull/26 . However, the docstring had the old parameter keys. It looks like this causes the example on https://api.python.langchain.com/en/latest/chat_models/langchain_aws.chat_models.bedrock.ChatBedrock.html#langchain_aws.chat_models.bedrock.ChatBedrock.guardrails to be wrong.

Fix ChatBedrock docs for guardrails

---

libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Added integration tests for `ChatBedrockConverse` for Meta provider. 
2 tests are primarily failing here. 
1. `test_tool_calling`, which is consistently returning a quoted string input value instead of an expected integer e.g., {input: '3'} instead of {input: 3}, thus failing the test. This needs further investigation to determine whether this is a bug with the Bedrock service or an expected behavior with Llama models when a numeric input is required. 
2. `test_tool_message_histories_list_content`, which is failing for several other providers as well, as Bedrock doesn't seem to allow conversation block and tool use blocks in the same turn.
```python
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the Converse operation: messages.1.content: …
```

Added integration tests for meta

---

libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Recently added an async variant of the tool calling test.
This appears to be a known issue for the Meta provider (see https://github.com/langchain-ai/langchain-aws/pull/274).

aws: xfail meta async test for converse

---

README.md

Minor update to README, to refer to ChatBedrock instead of BedrockLLM.

Updated to include Bedrock chat model

---

libs/aws/poetry.lock
libs/aws/pyproject.toml

Adds back numpy as dependency which was removed in #282. This is causing release errors, due to dependency of numpy in the Bedrock embeddings.

Adding back numpy to fix release errors.

---

libs/aws/langchain_aws/chat_models/bedrock.py

Fixed a minor regression in v0.2.9. Runs of `ChatBedrock` with missing or NoneType `model_id` get caught in the new `beta_use_converse_api` parameter check, which throws an ambiguous TypeError. 
This change restores the original behavior where ValidationError is thrown for absent `model_id`.

Fix model_id validation in ChatBedrock

---

libs/aws/langchain_aws/graphs/neptune_graph.py

Improved the graph schema retrieval performance of `NeptuneAnalyticsGraph` by using the [pg_schema](https://docs.aws.amazon.com/neptune-analytics/latest/userguide/custom-algorithms-property-graph-schema.html) algorithm.
Before:
After:

Improve performance of NeptuneAnalyticsGraph

---

libs/aws/langchain_aws/llms/bedrock.py

not sure how to add a test to this, since all tests that currently address "GUARDRAIL_INTERVENED" messages do not cover the callback section
this is related to https://github.com/langchain-ai/langchain-aws/issues/78

fixing references to re-enable guardrail callback

---

libs/aws/langchain_aws/__init__.py
libs/aws/langchain_aws/chains/__init__.py
libs/aws/langchain_aws/chains/graph_qa/__init__.py
libs/aws/langchain_aws/chains/graph_qa/neptune_cypher.py
libs/aws/langchain_aws/chains/graph_qa/neptune_sparql.py
libs/aws/langchain_aws/chains/graph_qa/prompts.py
libs/aws/langchain_aws/graphs/__init__.py

Replaces #306.
Adding new LCEL format chains `create_neptune_opencypher_qa_chain` and `create_neptune_sparql_qa_chain` for Amazon Neptune. 
These will replace the legacy [`NeptuneOpenCypherQAChain`](https://python.langchain.com/api_reference/community/chains/langchain_community.chains.graph_qa.neptune_cypher.NeptuneOpenCypherQAChain.html#langchain_community.chains.graph_qa.neptune_cypher.NeptuneOpenCypherQAChain) and [`NeptuneSparqlQAChain`](https://python.langchain.com/api_reference/community/chains/langchain_community.chains.graph_qa.neptune_sparql.NeptuneSparqlQAChain.html) chains in `langchain-community`.
To import, run:
```
from langchain_aws.chains import (
create_neptune_opencypher_qa_chain,
create_neptune_sparql_qa_chain,
)
```

Add reworked Neptune chains

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py

AWS Bedrock recently introduced support for latency optimization that greatly speeds up tokens/second response times for certain models being rolled out. This PR adds the ability to pass the config through langchain to make use of the faster model calls.
AWS Docs:
- https://docs.aws.amazon.com/bedrock/latest/userguide/latency-optimized-inference.html
Example usage compared to boto3
```python
client = boto3.client("bedrock-runtime")
response = client.converse(
modelId=model_id,
messages=[{"role": "user", "content": [{"text": query}]}],
performanceConfig={"latency": "optimized"|"standard"},
)
client = ChatBedrockConverse(
model_id=model_id,
performance_config={"latency": "optimized"|"standard"},
)
response = client.invoke(query)
```
Benchmarks I tried locally after the change. Langchain …

Add support for latency optimized performanceConfig

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py

Adding request metadata support for Converse API through ChatBedrock and ChatBedrockConverse
```
ChatBedrock(
model_id="us.anthropic.claude-3-5-sonnet-20241022-v2:0",  
region_name="us-east-1",
temperature=0.15,
max_tokens=100,
beta_use_converse_api=True,
model_kwargs={"request_metadata":{"priority": "High"}}
)
```
```
ChatBedrockConverse(
model_id="anthropic.claude-3-haiku-20240307-v1:0",
region_name="us-east-1",
request_metadata={"priority": "High"}
)
```

Adding request metadata support

---

libs/aws/langchain_aws/retrievers/bedrock.py
libs/aws/tests/unit_tests/retrievers/test_bedrock.py

Adds support for structured and multi-modal retrieval by updating the Bedrock retriever response parsing logic
1. Modularize retrieval logic in Bedrock retriever to separate a/ request creation b/ response parsing c/ search result to document conversion
2. Make the retrieval config clearly optional + make it clear that it can be either a dictionary or a Python object
3. Add TEXT, IMAGE, and ROW parsing for search results
4. Introduce broader testing regime to test more cases across all of the different output types
1. Added and executed new unit tests
2. Installed and ran manual local tests on a few existing Knowledge Bases

Support Structured and Multi-Modal Response Types in Bedrock Retriever

---

libs/aws/langchain_aws/chains/graph_qa/neptune_cypher.py
libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/langchain_aws/utils.py
libs/aws/tests/unit_tests/retrievers/test_bedrock.py

Fixes #314
The `get_num_tokens()` and `get_token_ids()` methods of `BedrockLLM` and `ChatBedrock` currently fail when used with Anthropic models and `anthropic>=0.39.0` installed. 
In such scenarios, this PR fixes `get_num_tokens()` and `get_token_ids()` by falling back to the base class implementations [in `BaseLanguageModel`](https://python.langchain.com/api_reference/core/language_models/langchain_core.language_models.base.BaseLanguageModel.html#langchain_core.language_models.base.BaseLanguageModel.get_num_tokens) and [in `BaseChatModel`](https://python.langchain.com/api_reference/core/language_models/langchain_core.language_models.chat_models.BaseChatModel.html#langchain_core.language_models.chat_models.BaseChatModel.get_num_tokens), which use the HuggingFace [GPT2 …

Fix Bedrock token count and IDs for Anthropic models

---

libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/tests/integration_tests/embeddings/test_bedrock_embeddings.py

The [Cohere embedding provider](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-embed.html) supports asking for multiple embeddings at the same time.
The current implementation of `embed_documents` always iterates across the submitted texts and attempts to embed them one-by-one.
This PR updates this `embed_documents` logic to check whether we are using the cohere provider, and if so request all of the embeddings at once.

Enhance `embed_documents` to make use of Cohere's ability to request multiple embeddings at once

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/langchain_aws/function_calling.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

Adding tool name as default tool descriptions if description is an empty string or not passed
Fixes #336

[Fix] Adding default description in tools

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/langchain_aws/llms/bedrock.py

The bedrock chat model has several logging statements that seem to be left over from someone debugging the code. Some of them result in the entire prompt being logged to the console, cluttering logging of applications leveraging the module. This PR removes said logging statements.

removed unecessary debug statements

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py

Added run_manager in stream method of ChatBedrockConverse. Added streaming flag handling for to enable converse streaming with ChatBedrock
Fixes #334 
```python
import boto3
from langchain_aws import ChatBedrock, ChatBedrockConverse
from langchain.callbacks.base import BaseCallbackHandler
from langchain_core.prompts import ChatPromptTemplate
streaming = True
session = boto3.session.Session()
bedrock_client = session.client("bedrock-runtime", region_name="us-east-1")
class MyCustomHandler(BaseCallbackHandler):
def on_llm_new_token(self, token: str, **kwargs) -> None:
print(f"My custom handler, token: {token}; Type of token: {type(token)}")
prompt = ChatPromptTemplate.from_messages(["Tell me a joke about {animal}"])
model = ChatBedrock(
client=bedrock_client, …
```

[Fix] streaming chatbedrock converseapi

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Update the ChatBedrock class to accept the user initiated Bedrock client.

[Fix] added missed client parameter in ChatBedrock

---

libs/aws/langchain_aws/__init__.py
libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/langchain_aws/document_compressors/rerank.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/langchain_aws/utils.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/unit_tests/document_compressors/test_rerank.py
libs/aws/tests/unit_tests/retrievers/test_bedrock.py

Fixes #308
Update the `ChatBedrock` class to handle the `region_name` parameter correctly.
* Modify `libs/aws/langchain_aws/chat_models/bedrock.py` to ensure the `region_name` parameter is passed to the `ChatBedrockConverse` class and add logic to take `region_name` from `AWS_REGION` environment variable if not provided.
* Add test cases in `libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py` to confirm that `ChatBedrockConverse` works with the `amazon.nova-pro-v1:0` model and takes `region_name` from `AWS_REGION` environment variable if not provided.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/langchain-ai/langchain-aws/pull/339?shareId=7fd95976-2f6d-4f1b-9585-7dc4c9d665d7).

Fix ChatBedrock integration with Amazon Bedrock model

---

libs/aws/langchain_aws/agents/base.py
libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/langchain_aws/llms/sagemaker_endpoint.py

- Not using the root logger lets the end user better control logging for specific packages and modules, e.g. by configuring `langchain_aws.llms.bedrock` to log at the `ERROR` level, but `langchain_aws.llms.bedrock` at the `DEBUG` level.
- Using `logger.exception` adds exception info to the [log record](https://docs.python.org/3/library/logging.html#logrecord-attributes). This is particularly useful if you want to use a library like [python-json-logger](https://pypi.org/project/python-json-logger/) or [structlog](https://github.com/hynek/structlog), where the exception info could be nicely formatted into an array/object.

Use `logger.exception` to log errors inside exception handlers and avoid logging from the root logger

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/langchain_aws/utils.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

This PR adds comprehensive support for Anthropic Claude 3.7 Sonnet's "thinking" feature, which allows the model to expose its reasoning process during inference. The implementation is based on the approach used in [langchain-anthropic](https://github.com/langchain-ai/langchain/blob/master/libs/partners/anthropic/langchain_anthropic/chat_models.py) and should provide more consistent API relative to https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#streaming-extended-thinking with more complete handling across both streaming and non-streaming modes than PR https://github.com/langchain-ai/langchain-aws/pull/372.
- Added support for `reasoning_content` blocks in responses
- Implemented handling of thinking-related delta types in streaming responses
- Added utility …

Add support for Anthropic Claude 3.7 Sonnet thinking

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

This pull request updates the streaming validator logic in our AWS Bedrock integration to align with the latest AWS documentation. According to the [AWS Bedrock Models Documentation](https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html), models from Anthropic, Cohere, AI21 Labs, Meta, and Mistral support streaming mode, while only specific Amazon models (those with IDs containing keywords like "nova-lite", "nova-micro", "nova-pro", "titan-text-express", "titan-text-lite", or "titan-text-premier") support streaming.
- **Streaming Validator Update:**  
Modified the `set_disable_streaming` validator in `ChatBedrockConverse` to:
- Recognize Meta, AI21 Labs, and Mistral models as having streaming enabled.
- For Amazon models, enable streaming only when the model ID …

Update Streaming Validator for AWS Bedrock Models

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Structured output will currently always raise a ValidationException when Claude 3.7 Sonnet's `thinking` is enabled, because we rely on forced tool use for structured output and this feature is not supported when `thinking` is enabled.
Here we:
- Emit a warning if `with_structured_output` is called when `thinking` is enabled.
- Raise `OutputParserException` if no tool calls are generated.
This is arguably preferable to raising an error in all cases.
```python
from langchain_aws import ChatBedrockConverse
from pydantic import BaseModel
class Person(BaseModel):
name: str
age: int
llm = ChatBedrockConverse(
model="us.anthropic.claude-3-7-sonnet-20250219-v1:0",
max_tokens=5000,
additional_model_request_fields={
"thinking": {"type": "enabled", "budget_tokens": 2000}
},
)
structured_llm = …
```

aws[patch]: allow structured output when thinking is enabled for Claude 3.7

---

.github/workflows/_release.yml

Updates the `mark_release` step in `_release.yml` to:
1. Add the package release binary and archive to the release assets.
2. Accommodate separate package releases for `langchain-aws` and `langgraph-checkpoint-aws`. Moving forward, release tags for both packages will follow the `{package-name}=={version}` convention.

Update tag and artifacts generation in release workflow

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

https://github.com/langchain-ai/langgraph/discussions/2161
Anthropic requires that tool result content blocks precede text in user messages. The functionality to merge messages does not account for this.
```python
from langchain_aws import ChatBedrock
from langchain_core.messages import (
AIMessage,
HumanMessage,
SystemMessage,
ToolMessage,
)
from langchain_core.tools import tool
@tool
def get_weather(location: str) -> str:
"""Get weather at a location."""
return "It's sunny."
system = SystemMessage("You are a helpful assistant.")
human = HumanMessage("What is the weather in Boston?")
ai = AIMessage(
"",
tool_calls=[
{"name": "get_weather", "id": "1", "args": {"location": "Boston, MA"}},
],
)
tool = ToolMessage(
"It's sunny.",
tool_call_id="1",
)
human_2 = HumanMessage("That doesn't look …
```

aws[patch]: fix ordering of tool result content blocks

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/__snapshots__/test_standard.ambr

- Increases the default worker thread count from `os.cpu_count() + 4` to `os.cpu_count() * 5` in `BedrockBase`.
- This worker thread count determines the number of Bedrock requests that can be awaited in parallel. Increasing this value makes all Bedrock model classes more capable in handling a large number of concurrent requests.
- Adds a new `max_parallel_requests` argument to allow users to tune the worker thread count to optimize request throughput.
I received a private report from a user trying to process multiple LLM requests in parallel via `ChatBedrock`. The user is using a M3 Macbook, and is using the `loop.create_task()` method on the event loop to send and handle requests concurrently.
However, the user noticed that after exceeding ~20 tasks, the time it took for all tasks to …

Increase default worker thread count and make it configurable

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/__snapshots__/test_standard.ambr

Reverts the unreleased `max_parallel_requests` attribute added in #391, as it is redundant with the [`max_concurrency`](https://python.langchain.com/api_reference/core/runnables/langchain_core.runnables.config.RunnableConfig.html#langchain_core.runnables.config.RunnableConfig.max_concurrency) option already available in RunnableConfig for batching calls.
In general, the Runnable async invoke and stream methods are not intended to be able to make multiple requests in parallel, and do not use `max_concurrency`. We should not attempt to skirt this restriction via a custom parameter, and instead recommend users to utilize the purpose-built [`abatch`](https://python.langchain.com/api_reference/core/runnables/langchain_core.runnables.base.Runnable.html#langchain_core.runnables.base.Runnable.abat …

Revert BedrockBase worker thread configuration

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

Related: #395
This PR updates `LLMInputOutputAdapter` to correctly handle streaming responses from DeepSeek-R1 when using `ChatBedrock`.

Support DeepSeek-R1 streaming with ChatBedrock

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes https://github.com/langchain-ai/langchain-aws/issues/395
DeepSeeks supports ConverseStream but not Streaming Tool Use: https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference-supported-models-features.html
Similar to https://github.com/langchain-ai/langchain-aws/pull/400 but for the ChatBedrockConverse. Added a test to ensure no_tools streaming is working. 
Tests pass, and manually testing appears to work as well.

Add DeepSeek-R1 'no_tools' streaming support for ChatBedrockConverse

---

libs/aws/langchain_aws/embeddings/bedrock.py

To fix bug with Cohere embedding models input_type for embedding a query rather than a document. #381 
Small change to add input_type to _embedding_func(), still defaults input_type to "search_document" to ensure that multi embedding and other functions are unchanged.

added input_type for cohere embedding models

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

This PR updates ChatBedrock's DeepSeek-R1 stream response handling, compensating for differences between the base model and distilled model formats.
For example, a base model stream chunk looks like:
```
{
"choices": [
{
"text": "hello",
"stop_reason": null
}
]
}
```
The Llama and Qwen distills both follow the format:
```
{
"choices": [
{
"index": 0,
"text": "hello",
"logprobs": null,
"finish_reason": ""
}
],
"model": "/opt/ml/model",
"system_fingerprint": "3.0.1-native",
"object": "text_completion",
"id": "",
"created": 1742011074
}
```

Fix ChatBedrock streaming with DeepSeek-R1 distilled models

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes https://github.com/langchain-ai/langchain-aws/issues/401
Claude 3.7 still works because signatures are always returned with those thinking blocks. DeepSeek thinking blocks do not contain signatures and the ValidationError indicates a signature must be included with thinking blocks.
According to Converse API docs:
> "Within the reasoningText field, the text fields describes the reasoning. The signature field is a hash of all the messages in the conversation and is a safeguard against tampering of the reasoning used by the model. You must include the signature and all previous messages in subsequent Converse requests. If any of the messages are changed, the response throws an error."
https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference-call.html
@3coins I posted …

Prevent sending thinking blocks with no signature with ChatBedrockConverse

---

libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/tests/integration_tests/embeddings/test_bedrock_embeddings.py

In a [previous PR](https://github.com/langchain-ai/langchain-aws/pull/350), I added support for retrieving more than one embedding at once from the Cohere embedding API.
@romenlee [pointed out](https://github.com/langchain-ai/langchain-aws/pull/350#issuecomment-2688770323) that this causes problems with a large number of texts. It looks like the [Cohere embedding API](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-embed.html) has a limit of either 96 texts, or 2048 characters.
This PR implements more intelligent batching that respects these limits -- it batches texts in chunks that are at most 96 texts or 2048 characters, submits them to the embedding API, and combines the results.
There is a complexity vs. efficiency tradeoff call to make here for the maintainers. …

fix: text and character limits on Cohere embedding API

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

Excludes tool calling spec from camelcase conversion.

---

libs/aws/langchain_aws/chat_models/sagemaker_endpoint.py
libs/aws/langchain_aws/document_compressors/rerank.py
libs/aws/langchain_aws/graphs/neptune_graph.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_standard.py

Follow-up to #360.
This PR updates the following classes to use the `create_aws_client` utility function, and/or accept additional Boto client parameters during initialization:
- `BedrockRerank`
- `ChatSagemakerEndpoint`
- `NeptuneGraph`
- `NeptuneAnalyticsGraph`

Update AWS client creation for additional chains

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Largely to support tracking token usage across models via a new [usage metadata callback handler](https://python.langchain.com/docs/how_to/chat_token_usage_tracking/#using-callbacks).
Standard tests were updated to enforce compatibility in https://github.com/langchain-ai/langchain/pull/30497.
Here we update `langchain-tests` to pick up the new test and update ChatBedrock and ChatBedrockConverse to pass.

aws[patch]: propagate model names to response metadata

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_standard.py

We're rolling out a standard format for content blocks for multi modal data (see https://github.com/langchain-ai/langchain/pull/30746).
Here we add support in ChatBedrock and ChatBedrockConverse.

aws[patch]: support standard format for multi-modal content blocks

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Following https://github.com/langchain-ai/langchain/pull/30887, these are no longer required to be stuffed in the `metadata` key.

aws[patch]: support extra keys on multi-modal content blocks

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/langchain_aws/function_calling.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

1. add prompt caching for tools to bedrock converse api
2. unit tests and integration tests have been added 
3. local run on unit tests and integration tests:
poetry run pytest tests/integration_tests/chat_models/test_bedrock_converse.py::test_tool_use_with_cache_point     
...
tests/integration_tests/chat_models/test_bedrock_converse.py .                                                             [100%]

Add support of Prompt Caching for tools

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/__snapshots__/test_standard.ambr
libs/aws/tests/unit_tests/chat_models/test_bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Implement a convenience for initialization that is common to most other LangChat chat models.
Here we catch params on init that are invalid according to Pydantic and store in the `model_kwargs` parameter (or `additional_model_request_fields` in the case of ChatBedrockConverse).
Consider initializing with a param that is not explicitly typed as an attribute:
```python
from langchain_aws import ChatBedrock, ChatBedrockConverse
thinking = {"type": "enabled", "budget_tokens": 2000}  # invalid param
llm_1 = ChatBedrock(
model="anthropic.claude-3-5-sonnet-20240620-v1:0",
thinking=thinking,
)
llm_2 = ChatBedrockConverse(
model="anthropic.claude-3-5-sonnet-20240620-v1:0",
thinking=thinking,
)
```
Currently, both of the above raise ValidationError.
After this change, ChatBedrock will transfer …

aws[patch]: support model_kwargs

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

Making convert_messages_to_prompt_anthropic work with messages or empty message list

Correctly handle empty input in ChatBedrock's Anthropic prompt adapter

---

libs/aws/langchain_aws/document_compressors/rerank.py
libs/aws/tests/unit_tests/document_compressors/test_rerank.py

Document(BaseMedia) has at least one more property that is currently dropped: "id". Could also be added explicitly.

rerank: preserve Document-fields

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes Issue #500: Incorrect nesting of `cachePoint` blocks inside `ToolMessage` causes Bedrock API request validation errors.
The `cachePoint` block is nested under `toolResult.content`, which is not allowed by Bedrock API:
```json
{
"role": "user",
"content": [
{
"toolResult": {
"content": [
{"text": "Tool response"},
{"cachePoint": {"type": "default"}}  // ❌ Invalid here!
],
"toolUseId": "xyz",
"status": "success"
}
}
]
}
```
This PR hoists the `cachePoint` block to be a top-level sibling entry within the message's content array:
```json
{
"role": "user",
"content": [
{
"toolResult": {
"content": [
{"text": "Tool response"}
],
"toolUseId": "xyz",
"status": "success"
}
},
{
"cachePoint": {"type": "default"}  // ✅ Valid placement
}
]
}
```
---
- In `_messages_to_bedrock`, …

fix(bedrock): hoist cachePoint blocks out of ToolMessage content to comply with Bedrock API

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

Fixes Issue: https://github.com/langchain-ai/langchain-aws/issues/501: Inaccurate re-ordering of message content when using ChatPromptAdapter.format_messages
- Modified `__format_anthropic_messages` in bedrock.py
- Renamed `text_blocks` to `native_blocks`
- Insert the image content into `native_blocks` instead of `tool_blocks`
- Added test `test__format_anthropic_messages_preserves_content_order`
Ignore that 1st force push, had to re-set my name and email on the commit.
Fixes: #501

fix(bedrock): Interleave Image Content in ChatPromptAdapter

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

Similar to https://github.com/langchain-ai/langchain-aws/issues/141, ChatBedrock was failing when an AIMessage had a tool_calls defined but whose content was not a str. Have not yet run integration tests but unit tests are passing.
Sample that would previously fail:
```python
import logging
from langchain_aws import ChatBedrock
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.tools import tool
@tool
def search_google(query: str) -> str:
"""Search Google for the given query"""
return "Paris"
llm = ChatBedrock(
model_id="anthropic.claude-3-5-sonnet-20240620-v1:0",
temperature=0.1,
max_tokens=2048,
)
llm_with_tools = llm.bind_tools([search_google])
messages = [
SystemMessage(content="You are a helpful assistant."), …
```

bug: Ensure anthropic AIMessages with tool_calls work if their content is not a str

---

README.md

This PR fixes incorrect casing for PyPI (Python Package Index) and makes it consistent with the other uses within the README.

Fix acronym casing for PyPI

---

libs/aws/langchain_aws/vectorstores/inmemorydb/base.py

In latest version of redis-py 6.2, it is using this path `index_definition` instead of `indexDefinition` from https://github.com/redis/redis-py/blob/513c8d0f61460ef690d3218805e9a4a2ee675af9/redis/commands/search/index_definition.py#L11
This has been tested with Python 3.12.10 with Redis 6.2.0

Update base.py on redis-py index definition path

---

README.md

Update README for Bedrock Agentcore toolkits

---

libs/aws/langchain_aws/graphs/neptune_graph.py

Fixed Issue #552 by adding proper passing of the parameters through into the query call when using Neptune database

Fixed Issue #552 - Parameterized Query Support in NDB

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

We introduce a new flag, guard_last_turn_only, which applies the selective guardrail for only the last user message. For advanced use cases, we also allow the dev to pass in raw (Bedrock) message blocks.
Issue Link: https://github.com/langchain-ai/langchain-aws/issues/540

Add Support for GuardRailConverseContentBlock

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

Prompt caching was initially added [here](https://github.com/langchain-ai/langchain-aws/commit/0067b861a47af295683e101c98f9f6719f514728#diff-78c2abdea066a69391d4a156ea3d401a6fec2cb8ea8f578e2d42e7888a615d7c) but seems like it wasn't supported on system messages at that time. It is now!
https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#large-context-caching-example
This PR preserves `SystemMessage` content as a list of blocks rather than converting it into a single concatenated string.  This will make sure the caching param is retained.

Support prompt caching on system messages

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

This PR fixes the issue when running a agent using tools with application inference profile of Claude Sonnet 3.7 as input. Note that using regional inference profile is working well, and only application inference profile (AIP) will not return any tools use information. 
Langchain needs to identify the model id of the foundation model but fails to detect the foundation model from the input AIP ARN (e.g., `arn:aws:bedrock:us-east-1:111111484058:application-inference-profile/c3myu2h6fllr`), while regional inference profile contains the foundation model name `us.anthropic.claude-3-7-sonnet-20250219-v1:0` and can be easily used to identify the base model id. Therefore, regional inference profile is working well while AIP is not. 
To identify the foundation model used in AIP, we need to call …

Fix: Bedrock Application Inference ARN breaks Claude Sonnet tools usage

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

This PR fixed the streaming issue with ChatBedrockConverse when input is Application Inference Profile (AIP). The issue happened because langchain-aws fails to identify the foundation model used in AIP (e.g., `arn:aws:bedrock:us-east-1:111111484058:application-inference-profile/c3myu2h6fllr`), therefore, it cannot set the streaming_support flag for the AIP correctly. So the entire response was returned to user as a whole rather than streaming the response back. 
We have to create a Bedrock client to call Bedrock get_inference_profile control plane [API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bedrock/client/get_inference_profile.html), and parse the foundation model id from the response. However, the existing `set_disable_streaming` function works on the …

Fix: Bedrock Application Inference Profile (AIP) is not streaming response with ChatBedrockConverse

---

libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/__init__.py
libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/utils.py
libs/langgraph-checkpoint-aws/poetry.lock
libs/langgraph-checkpoint-aws/pyproject.toml

Fixes: #546 
This is a patch release to unblock usage of `langgraph-checkpoint-aws` with LangGraph >=0.5.
A more comprehensive update for LangGraph >=0.5 compatibility is pending investigation with https://github.com/langchain-ai/langchain-aws/pull/550.

langgraph-checkpoint-aws: release 0.1.1

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes: #573 
Updating ChatBedrockConverse to set `disable_streaming=False` by default for `gpt-oss`, as Bedrock now supports streaming (with tool calls) for these models.

Enable ChatBedrockConverse streaming for OpenAI gpt-oss models

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes: #591 
The ToolConfig ValidationException happens when using summarization nodes with `create_react_agent`. The issue is that the summarization node gets messages from the react agent that contain tool calls, but the summarizer is usually a different LLM client and isn't bound with the main agent's tools. So when the summarization model calls Bedrock Converse API, it fails because there are tool blocks but no `toolConfig`.
Instead of just throwing a ValidationException, this change converts tool blocks to text format when `toolConfig` is missing. This way the summarization model still gets the tool call context but in a text format.
I considered just removing the tool messages completely, but that would make the summarization node lose context about what tools were called and their …

fix(bedrock_converse): handle tool blocks without toolConfig

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

AWS has added inference profiles that begin with "amer" and "global". This change allow ChatBedrock to correctly recognize such inference profiles

fix: add support for `amer` and `global` bedrock cross region inference profiles

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Related: #620 
Allows passing `tool_choice` values for compatible Llama4 and Llama3 models when using ChatBedrockConverse.

Add tool_choice config for Llama models

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py

Addresses #498 for ChatBedrock.

Support multiple system messages for Anthropic

---

libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/async_saver.py
libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/async_session.py
libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/saver.py
libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/session.py
libs/langgraph-checkpoint-aws/langgraph_checkpoint_aws/utils.py
libs/langgraph-checkpoint-aws/tests/unit_tests/test_async_saver.py
libs/langgraph-checkpoint-aws/tests/unit_tests/test_async_session.py
libs/langgraph-checkpoint-aws/tests/unit_tests/test_saver.py
libs/langgraph-checkpoint-aws/tests/unit_tests/test_session.py

Fixes: #619
Added an extra parameter as input for the BedrockSessionSaver to pass customized credential session info.
This will allow users to pass their own pre configured boto3 session like this:
```
saver = BedrockSessionSaver(region_name="us-west-2", aws_access_key_id=..., aws_secret_access_key=...)
session = boto3.Session(profile_name="my-custom-profile")
saver = BedrockSessionSaver(session=session)
```
So when a session is provided, it's used directly instead of creating a new one from individual credential parameters.

feat(checkpointer): add session parameter support

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes: #653
Add get_num_tokens_from_messages to ChatBedrockConverse using the new AWS Bedrock count_tokens API.
- Implements a Bedrock specific override of BaseLanguageModel.get_num_tokens_from_messages.
- If the model doesn't support Bedrock's count_tokens API, or the API call fails, it fall back to the base implementation (super().get_num_tokens_from_messages).
- Tools are ignored for now because count_tokens doesn't support tool schemas.
Example:
```
model = ChatBedrockConverse(model_id="us.anthropic.claude-3-5-haiku-20241022-v1:0")
tokens = llm.get_num_tokens_from_messages([HumanMessage("hi"), AIMessage("hello")])
```

Support CountTokens in ChatBedrockConverse
