libs/aws/langchain_aws/__init__.py
libs/aws/langchain_aws/embeddings/__init__.py
libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/integration_tests/embeddings/test_bedrock_embeddings.py

Added bedrock embeddings

---

libs/aws/langchain_aws/embeddings/bedrock.py
libs/aws/tests/integration_tests/embeddings/test_bedrock_embeddings.py

Fixes specifying model_kwargs for embeddings

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Closes https://github.com/langchain-ai/langchain-aws/issues/113.

aws[patch]: retain snake case for input schemas

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Fixes streaming for llama3 models.

---

libs/aws/langchain_aws/llms/bedrock.py

Fixes support for custom/provisioned models which supply an arn as model id.

Fixes model id for custom model arns

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fix #130 
Note this updates the behavior for all models, not just anthropic.

aws[patch]: merge messages in chat bedrock converse

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

aws[patch]: fix streaming and tool choice for non-anthropic models

---

README.md

Updating README to include support for Bedrock Agents.

Updating README to include support for Bedrock Agents

---

libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/unit_tests/chat_models/test_bedrock.py
libs/aws/tests/unit_tests/llms/test_bedrock.py

Fixes get provider for model_ids with region prefix. Added unit tests.

---

libs/aws/langchain_aws/retrievers/kendra.py

Resolves https://github.com/langchain-ai/langchain-aws/issues/202

aws[patch]: set defaults on DocumentAttributeValue

---

.github/workflows/_release.yml

aws[patch]: fix release workflow

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/tests/unit_tests/chat_models/__snapshots__/test_bedrock_converse.ambr

Backport for PR #212 
Note: Dependent on https://github.com/langchain-ai/langchain/pull/27114 to fix the tests failing in CI.

Backport pr 212

---

.github/workflows/_integration_test.yml

Adds a new workflow to run integration tests from the actions section.

Added an integration test workflow

---

libs/aws/pyproject.toml

Updates version to v0.2.3

---

libs/aws/pyproject.toml

Updates version to v0.2.4

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

bind tools in openai format so that runs with tools are traced in a standard format

aws[patch]: bind tools in openai format

---

libs/aws/pyproject.toml

Updates version to 0.2.7

---

libs/aws/langchain_aws/chains/graph_qa/neptune_cypher.py
libs/aws/langchain_aws/chains/graph_qa/neptune_sparql.py

Updated `create_neptune_opencypher_qa_chain` and `create_neptune_sparql_qa_chain` to accept base string type queries on invoke, in addition to the current dict format. 
This restores consistency with the input format of the older `langchain-community` Neptune chains.

Add string input support for revised Neptune chains

---

libs/aws/tests/integration_tests/retrievers/test_amazon_knowledgebases_retriever.py

Fixes integration test failure introduced with #317

Fixed integration tests for bedrock retriever.

---

.github/dependabot.yml

Continuing on the work in #346. I have enabled dependabot alerts in the settings.

Added config for dependabot grouped updates.

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/unit_tests/chat_models/test_bedrock_converse.py

Fixes #432 
Here is the sample test code from #432.
```python
import asyncio
from langchain_aws import ChatBedrockConverse
from langchain_core.tools import tool
from langgraph.prebuilt import create_react_agent
prompt = """
You are a helpful assistant used for debugging.
You will say short messages to reply when I ask, or use your fake tool when I ask you to.
"""
model = ChatBedrockConverse(
model="us.anthropic.claude-3-7-sonnet-20250219-v1:0",
max_tokens=5000,
region_name="us-east-1",
additional_model_request_fields={
"thinking": {"type": "enabled", "budget_tokens": 2000}
},
)
@tool
def fake_tool(fake_input_1: str, fake_input_2: int) -> str:
"this is fake tool, only use it when requested"
return "fake_output"
agent = create_react_agent(model, [fake_tool], prompt=prompt, …
```

Removes nested type for text/signature in reasoning_content.

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Following https://github.com/langchain-ai/langchain-aws/pull/437

aws[patch]: support snake_case arguments in tools in ChatBedrockConverse

---

.github/workflows/_release.yml

Release pipeline is [blocked](https://github.com/langchain-ai/langchain-aws/actions/runs/14117529781/job/39551249220) (this is a guess at a solution).

infra: unset AWS_DEFAULT_REGION in release pipeline

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

Fix bound Anthropic thinking params in ChatBedrockConverse

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/poetry.lock
libs/aws/pyproject.toml
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Requires https://github.com/langchain-ai/langchain/pull/30979

aws[patch]: support openai format for PDF documents

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/langchain_aws/llms/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_standard.py

Tests pass for ChatBedrockConverse

aws[patch]: fix tool calling and structured output for Claude 4 / ChatBedrock

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

feat: add nova-premier model to streaming-compatible models

---

.github/workflows/_compile_integration_test.yml
.github/workflows/_integration_test.yml
.github/workflows/_lint.yml
.github/workflows/_release.yml
.github/workflows/_test.yml
.github/workflows/_test_release.yml
.github/workflows/check_diffs.yml

Addresses CodeQL scan alerts related to `CWE-275`.
New CodeQL scan passes on my fork: https://github.com/michaelnchin/langchain-aws/actions/runs/16740128948/job/47386808821

infra: Minimal permissions for workflow jobs

---

libs/aws/langchain_aws/chat_models/bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock.py

Fixes #541 
- track guardrails interventions during streaming operations
- call callback handlers with trace info when guardrails intervenes

fix: add guardrails trace support for ChatBedrock streaming (#541)

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Fixes #486
Supersedes PR https://github.com/langchain-ai/langchain-aws/pull/491 - full credit goes to SYED-M-HUSSAIN for the original fix

fix: Return ChatBedrockConverse streaming content as str instead of list

---

.github/scripts/get_min_versions.py
libs/aws/langchain_aws/tools/code_interpreter_toolkit.py
samples/agents/agents_with_nova.ipynb
samples/inmemory/semantic_cache.ipynb

Fixed typos.

---

libs/aws/langchain_aws/chat_models/bedrock_converse.py

`AIMessage("", tool_calls=[...])` is a common representation for messages with tool calls— e.g., from chat completions APIs.
Following https://github.com/langchain-ai/langchain-aws/pull/593, these get translated into
```
{'role': 'assistant', 'content': [{'text': '.'}, {'toolUse': ...}]}
```
which some Converse providers reject (Meta and Mistral, see failed test run [here](https://github.com/langchain-ai/langchain-aws/actions/runs/17602834165/job/50007989000)).
Here we patch this specific case, removing `{"text": "."}` blocks if there are tool calls and that's the only content.
This is a hack, open to other solutions.

aws(patch): remove empty content when upserting tool calls

---

libs/aws/tests/integration_tests/chat_models/test_bedrock.py
libs/aws/tests/integration_tests/chat_models/test_bedrock_converse.py

Add chat model integration tests for multiple system messages

---

libs/langgraph-checkpoint-aws/README.md

Update README for LangGraph Checkpoint AWS
